<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>multiespectral_acquire_gui</name>
  <version>0.0.0</version>
  <description>Flask-based GUI to handle cameras using the multiespectral_acquire package.</description>
  <maintainer email="enrique.he.ag@gmail.com">quique</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>multiespectral_acquire</depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-pyyaml</exec_depend>
  <exec_depend>python3-flask</exec_depend>
  <exec_depend>python3-flask-socketio</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
